version: "3"
networks:
  nocobase:
    driver: bridge
services:
  adminer:
    image: adminer
    restart: always
    networks:
      - nocobase
    ports:
      - ${ADMINER_PORT}:8080
    volumes:
      - ./docker/adminer/login-sqlite-plugin.php:/var/www/html/plugins-enabled/login-sqlite-plugin.php
      - ./:/var/www/app
  postgres:
    image: postgres:10
    restart: always
    ports:
      - "${DB_POSTGRES_PORT}:5432"
    networks:
      - nocobase
    command: postgres -c wal_level=logical
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
  nocobase:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - nocobase
    command: [ "yarn", "start" ]
    working_dir: /app
    env_file: ./.env
    volumes:
      - ./:/app
    expose:
      - 8000
    ports:
      - "${APP_PORT}:8000"