name: Aliyun Container Registry

on:
  push:
    branches:
      - 'main'
      - 'develop'
    paths:
      - 'packages/**'
  pull_request:
    branches:
      - '**'
    paths:
      - 'packages/**'

jobs:
  push-acr:
    runs-on: ubuntu-latest
    services:
      verdaccio:
        image: verdaccio/verdaccio
        ports:
          - 4873:4873
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.SUBMODULE_SSH_KEY }}
          submodules: true
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: network=host
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            nocobase/nocobase
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ALI_DOCKER_REGISTRY }}
          username: ${{ secrets.ALI_DOCKER_USERNAME }}
          password: ${{ secrets.ALI_DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.acr
          build-args: |
            VERDACCIO_URL=http://localhost:4873/
            COMMIT_HASH=${GITHUB_SHA}
          push: true
          tags: ${{ secrets.ALI_DOCKER_REGISTRY }}/${{ steps.meta.outputs.tags }}

      - name: Save PR number
        env:
          PR_NUMBER: ${{ github.event.number }}
        run: |
          mkdir -p ./pr
          echo $PR_NUMBER > ./pr/pr_number
      - uses: actions/upload-artifact@v3
        with:
          name: pr_number
          path: pr/

      - name: Save image tag
        env:
          IMAGE_TAG: ${{ steps.meta.outputs.tags }}
        run: |
          mkdir -p ./image
          echo $IMAGE_TAG > ./image/image_tag
      - uses: actions/upload-artifact@v3
        with:
          name: image_tag
          path: image/

      - name: text message
        if: github.event_name == 'pull_request'
        uses: foxundermoon/feishu-action@v2
        with:
          url: ${{ secrets.PR_FEISHU_BOT_WEBHOOK_URL }}
          msg_type: text
          content: |
            text: |
              地址：${{ github.event.pull_request.html_url }}
              标题：${{ github.event.pull_request.title }}
              内容：${{ github.event.pull_request.body }}
              分支：${{ github.event.pull_request.head.ref }}
              触发者：${{ github.triggering_actor }}
              ----------------------------------------------
              正在自动部署环境-稍后访问地址：http://${{ secrets.deploy_host }}:1${{ github.event.number }}
              -----------------------------------------------
              请及时更新任务系统的任务状态：https://tasks.nocobase.com/
