name: NocoBase Backend Test

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
    paths:
      - 'package.json'
      - '**/yarn.lock'
      - 'packages/core/acl/**'
      - 'packages/core/actions/**'
      - 'packages/core/database/**'
      - 'packages/core/resourcer/**'
      - 'packages/core/data-source-manager/**'
      - 'packages/core/server/**'
      - 'packages/core/utils/**'
      - 'packages/plugins/**/src/server/**'
      - '.github/workflows/nocobase-test-backend.yml'
  pull_request:
    paths:
      - 'package.json'
      - '**/yarn.lock'
      - 'packages/core/acl/**'
      - 'packages/core/actions/**'
      - 'packages/core/database/**'
      - 'packages/core/resourcer/**'
      - 'packages/core/data-source-manager/**'
      - 'packages/core/server/**'
      - 'packages/core/utils/**'
      - 'packages/plugins/**/src/server/**'
      - '.github/workflows/nocobase-test-backend.yml'

jobs:
  postgres-test:
    strategy:
      matrix:
        node_version: ['20']
        underscored: [true]
        # schema: [public]
        # collection_schema: [public]
    runs-on: ubuntu-20.04
    container: node:${{ matrix.node_version }}
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:11
        # Provide the password for postgres
        env:
          POSTGRES_USER: nocobase
          POSTGRES_PASSWORD: password
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: rm
        run: |
          apt-get update && apt-get install -y sudo
          rm -rf "/usr/local/share/boost"
          rm -rf "$AGENT_TOOLSDIRECTORY"
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: true
          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
          cache: 'yarn'

      - name: Install project dependencies
        run: yarn install
      - name: Test with postgres
        run: |
          yarn test --server
        env:
          LOGGER_LEVEL: error
          DB_DIALECT: postgres
          DB_HOST: postgres
          DB_PORT: 5432
          DB_USER: nocobase
          DB_PASSWORD: password
          DB_DATABASE: nocobase
          DB_UNDERSCORED: ${{ matrix.underscored }}
          # DB_SCHEMA: ${{ matrix.schema }}
          # COLLECTION_MANAGER_SCHEMA: ${{ matrix.collection_schema }}
          DB_TEST_DISTRIBUTOR_PORT: 23450
          DB_TEST_PREFIX: test_
    timeout-minutes: 60
