name: Nocobase Build Test

on:
  push:
    branches:
      - 'main'
      - 'develop'
    paths:
      - 'packages/**'
  pull_request:
    branches:
      - '**'
    paths:
      - 'packages/**'

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Checkout pro-plugins
        uses: actions/checkout@v4
        with:
          repository: nocobase/pro-plugins
          ref: main
          path: packages/pro-plugins
          ssh-key: ${{ secrets.SUBMODULE_SSH_KEY }}
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'
      - run: yarn --frozen-lockfile
      - run: yarn build
        env:
          __E2E__: true # e2e will be reusing this workflow, so we need to set this flag to true
      - uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: packages/**/{es,lib,dist}/
    timeout-minutes: 30
