name: Release

on:
  push:

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    container: node:16
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: publish npmjs.org
        run: |
          git config --global user.email "test@mail.com"
          git config --global user.name "test"
