name: Release

on:
  push:

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    container: node:16
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: publish npmjs.org
        run: |
          rm -rf .git
          git init
          git add .
          git commit -m "chore(versions): test publish packages xxx"